[phases.setup]
nixPkgs = ["dotnet-sdk_8"]

[phases.build]
workdir = "CitySecrets"
cmds = [
    "dotnet restore",
    "dotnet publish -c Release -o ../out"
]

[start]
cmd = "dotnet out/CitySecrets.dll"
