[phases.setup]
nixPkgs = ["dotnet-sdk_8"]

[phases.build]
cmds = [
    "cd CitySecrets && dotnet restore",
    "cd CitySecrets && dotnet publish -c Release -o ../out"
]

[start]
cmd = "dotnet out/CitySecrets.dll"
